[gov_officials]
delegate = 'ProfessorHenn'
pm = 'Heliseum'
mofa = 'Welly'
mod = 'flowerpetal'
moc = 'Of_the_Ages'
moi = 'Trivalve'
owl_director = 'Erstavik'
coa = 'KrisKringle'
hc_chief_justice = 'Griffindor'
hc_justices = ['KrisKringle', 'Belschaft', 'Griffindor', 'Pronoun', 'Welly']
crs = ['Anjo', 'KrisKringle', 'ProfessorHenn', 'Pronoun']
spcg = [
    "Amerion",
    'Aidenfieeld',
    'Anjo',
    'lordnwahs',
    'Griffindor',
    'Land Without Shrimp',
    'PenguinPies',
]
citcomm = ['Anjo', 'Pronoun', 'Griffindor']
admiralty = ['ConcreteSlab', "Heliseum"]

[people_info]
[people_info.Amerion]
nation = 'Amerion'
discord_handle = 'amerion'
[people_info.Aidenfieeld]
nation = 'Aidenfieeld'
discord_handle = 'Aidenfieeld#7386'
[people_info.'Anjo']
nation = 'Tepertopia'
discord_handle = 'anjo0803'
[people_info.'Belschaft']
nation = 'Belschaft'
discord_handle = 'belschaft'
[people_info.'ConcreteSlab']
nation = 'Concrete Slab'
discord_handle = 'concrete.slab'
[people_info.'Erstavik']
nation = 'Erstavik'
discord_handle = 'urcwiki'
[people_info.'Heliseum']
nation = 'Heliseum'
discord_handle = 'heliseum'
[people_info.'Griffindor']
nation = 'Ebonhand'
discord_handle = '.griffindor'
[people_info.'KrisKringle']
nation = 'Kringalia'
discord_handle = 'kris_KrisKringle'
[people_info.'Land Without Shrimp']
nation = 'Land Without Shrimp'
discord_handle = 'sonofthunder7'
[people_info.'lordnwahs']
nation = 'Differences-In-Differences'
discord_handle = 'lordnwahs'
[people_info.'Pronoun']
nation = 'Esfalsa'
discord_handle = 'pronoun'
[people_info.'flowerpetal']
nation = 'Purple Hyacinth'
discord_handle = 'flowerpetal'
[people_info.'PenguinPies']
nation = 'PenguinPies'
discord_handle = 'ladypenguin55'
[people_info.'ProfessorHenn']
nation = 'Sporaltryus'
discord_handle = 'professorhenn'
[people_info.'Of_the_Ages']
nation = 'The Age of Utopia'
discord_handle = 'the_age_of_utopia'
[people_info.'Tsunamy']
nation = 'Tsunamy'
discord_handle = 'tsu_namy'
[people_info.'Trivalve']
nation = 'Trivalve'
discord_handle = 'eskie0'
[people_info.'Welly']
nation = 'Grace Wellesley Thayer'
discord_handle = 'wellythayer'
