[gov_officials]
delegate = 'Griffindor'
pm = 'lordnwahs'
dep_pm = 'ProfessorHenn'
mofa = 'Concrete Slab'
mod = 'Coltranius'
moc = 'xshotss'
moi = 'maluhia'
moe = 'NoOne'
owl_director = 'lordnwahs'
hc_chief_justice = 'Kringle'
hc_justices = ['Kringle', 'Belschaft', 'Griffindor', 'Pronoun']
coa = 'BlockBuster2K43'
crs = ['Amerion', 'Anjo', 'Em', 'HumanSanity', 'Kringle', 'Tsunamy']
spcg = [
    'Aidenfieeld',
    'Amerion',
    'Anjo',
    'Griffindor',
    'Land Without Shrimp',
    'ProfessorHenn',
    'Tsunamy',
]
citcomm = ['Anjo', 'Pronoun', 'Griffindor']
cabinet_advisors = []
admiralty = ['HumanSanity']

[people_info]
[people_info.Aidenfieeld]
nation = 'Aidenfieeld'
discord_handle = 'Aidenfieeld#7386'
[people_info.'Amerion']
nation = 'Amerion'
discord_handle = 'amerion'
[people_info.'Anjo']
nation = 'Tepertopia'
discord_handle = 'anjo0803'
[people_info.'Belschaft']
nation = 'Belschaft'
discord_handle = 'belschaft'
[people_info.'BlockBuster2K43']
nation = 'Great Lothian'
discord_handle = 'blockbuster2k43'
[people_info.'Concrete Slab']
nation = 'Concrete Slab'
discord_handle = 'concrete.slab'
[people_info.'Coltranius']
nation = 'The Lombard League'
discord_handle = 'ordofdiscs'
[people_info.'Em']
nation = 'Qvait'
discord_handle = 'gamingberserkr'
[people_info.'Griffindor']
nation = 'Ebonhand'
discord_handle = '.griffindor'
[people_info.'HumanSanity']
nation = 'HumanSanity'
discord_handle = 'humansanity'
[people_info.'Kringle']
nation = 'Kringalia'
discord_handle = 'kris_kringle'
[people_info.'Land Without Shrimp']
nation = 'Land Without Shrimp'
discord_handle = 'sonofthunder7'
[people_info.'lordnwahs']
nation = 'Differences-In-Differences'
discord_handle = 'lordnwahs'
[people_info.'maluhia']
nation = 'Lile Ulie Islands'
discord_handle = 'apresvous.'
[people_info.'NoOne']
nation = '7 Trees'
discord_handle = 'no_one_7777'
[people_info.'PenguinPies']
nation = 'PenguinPies'
discord_handle = 'ladypenguin55'
[people_info.'ProfessorHenn']
nation = 'Sporaltryus'
discord_handle = 'professorhenn'
[people_info.'Pronoun']
nation = 'Esfalsa'
discord_handle = 'pronoun'
[people_info.'Tsunamy']
nation = 'Tsunamy'
discord_handle = 'tsu_namy'
[people_info.'xshotss']
nation = 'Peoples Guerilla Armed Coalition'
discord_handle = '.jaywalkerr.'
