[coalition_of_the_south_pacific.welcome]
ns_id = "1192500"
title = "Introduction to NationStates and the South Pacific (Click here if you are new!)"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.welcome_long]
ns_id = "1568602"
title = "Introduction to the South Pacific (long version)"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.government_intro]
ns_id = "1192502"
title = "Introduction to the Government of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.factbook]
ns_id = "1192534"
title = "The Coalition of the South Pacific's Factbook"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.get_involved]
ns_id = "1192503"
title = "Get Involved in the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.guide_index]
ns_id = "1230616"
title = "List of guides about NationStates and the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.politics_guide]
ns_id = "1199302"
title = "Beginner guide to politics in the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.glossary]
ns_id = "1565638"
title = "Glossary of NationStates and TSP terms"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.elections]
ns_id = "1192504"
title = "Elections in the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.elections_guide]
ns_id = "1192516"
title = "Beginner guide to Elections in the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.elections_voting_methods]
ns_id = "1192517"
title = "Election voting methods explained"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.media_services]
ns_id = "1192505"
title = "List of media services in the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.index]
ns_id = "1237123"
title = "Index to every dispatch about the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.assembly_intro]
ns_id = "1192506"
title = "The Assembly of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.assembly_guide]
ns_id = "1192509"
title = "Beginner guide to the Assembly of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.assembly_procedures]
ns_id = "1192510"
title = "Legislative Procedures of the Assembly of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.assembly_details]
ns_id = "1192515"
title = "Details on the powers of the Assembly of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.cabinet_intro]
ns_id = "1192519"
title = "The Executive Branch of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.cabinet_elections]
ns_id = "1192520"
title = "Cabinet elections in the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.cabinet_details]
ns_id = "1192521"
title = "Details on the working of the executive branch"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.court_intro]
ns_id = "1192522"
title = "The High Court of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.court_details]
ns_id = "1192523"
title = "Details on the powers of the High Court of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.court_procedures]
ns_id = "1192524"
title = "Procedures of the High Court of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.court_guide]
ns_id = "1192525"
title = "Beginner guide to the High Court of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.indie_intro]
ns_id = "1205793"
title = "Independent institutions of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.crs_intro]
ns_id = "1192526"
title = "The Council on Regional Security of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.proscriptions]
ns_id = "1220344"
title = "Regions proscribed by the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.legcomm]
ns_id = "1192527"
title = "The Legislator Committee of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.election_commission]
ns_id = "1212829"
title = "The Election Commission of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.coa]
ns_id = "1192528"
title = "The Chair of Assembly of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.delegate_intro]
ns_id = "1192529"
title = "The Delegate of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.delegate_details]
ns_id = "1192530"
title = "Details on the working of the Delegate of the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.delegate_elections]
ns_id = "1192531"
title = "Delegate elections in the South Pacific"
category = "meta"
subcategory = "gameplay"

[coalition_of_the_south_pacific.law_index]
ns_id = "1192536"
title = "Laws of the South Pacific"
category = "meta"
subcategory = "gameplay"
